import { LegalDocument } from "@/components/legal/legal-document";

export default function SiteTermsPage() {
  return (
    <LegalDocument
      title="Site Terms"
      description="These terms describe the basic rules for using CommerceChat-powered chat experiences."
      sections={[
        {
          heading: "Using The Chat",
          body:
            "The chatbot helps answer questions, recommend products, and support shopping workflows. Responses may be generated by AI and should be reviewed before relying on them for important decisions.",
        },
        {
          heading: "Your Responsibility",
          body:
            "You agree not to submit unlawful, harmful, confidential, or sensitive personal information unless it is necessary for the service you are requesting.",
        },
        {
          heading: "Service Availability",
          body:
            "The chatbot may be unavailable, delayed, or inaccurate at times. Store owners remain responsible for final product, pricing, policy, and order information.",
        },
      ]}
    />
  );
}
