import { LegalDocument } from "@/components/legal/legal-document";

export default function ResponsibleAiPage() {
  return (
    <LegalDocument
      title="Responsible AI Policy"
      description="This policy describes how CommerceChat aims to use AI responsibly in shopping conversations."
      sections={[
        {
          heading: "AI-Generated Responses",
          body:
            "Chatbot responses may be generated by AI using store configuration, catalog data, website content, and conversation context. AI can make mistakes, so critical information should be verified.",
        },
        {
          heading: "Human Oversight",
          body:
            "Store teams can review conversations and take over when needed. The chatbot should not replace professional, legal, medical, financial, or safety advice.",
        },
        {
          heading: "Safety And Fairness",
          body:
            "We design the chatbot to avoid harmful instructions, respect user privacy, and provide relevant, transparent shopping support across tenants.",
        },
      ]}
    />
  );
}
