/** Routes backed by real Lambda handlers + DynamoDB */
export const IMPLEMENTED_ROUTES = [
  "GET /health",
  "POST /auth/signup",
  "POST /auth/login",
  "POST /auth/refresh",
  "POST /auth/logout",
  "POST /auth/forgot-password",
  "POST /auth/reset-password",
  "POST /auth/resend-verification",
  "POST /auth/invite",
  "POST /auth/accept-invite",
  "GET /auth/me",
  "POST /auth/verify-email",
  "GET /api/v1/tenants/me",
  "PATCH /api/v1/tenants/me",
  "POST /api/v1/tenants/me/logo",
  "POST /api/v1/tenants/me/logo/presign",
  "POST /api/v1/tenants/me/logo/complete",
  "GET /api/v1/tenants/me/config",
  "PATCH /api/v1/tenants/me/config",
  "GET /api/v1/tenants/me/limits",
  "GET /api/v1/onboarding",
  "PATCH /api/v1/onboarding/step",
  "POST /api/v1/onboarding/test-chat",
  "GET /api/v1/knowledge/sources",
  "POST /api/v1/knowledge/sources",
  "DELETE /api/v1/knowledge/sources/:id",
  "POST /api/v1/knowledge/sources/:id/sync",
  "GET /api/v1/knowledge/jobs",
  "GET /api/v1/knowledge/jobs/:id",
  "GET /api/v1/knowledge/faq",
  "POST /api/v1/knowledge/faq",
  "GET /api/v1/knowledge/page-voice",
  "PATCH /api/v1/knowledge/page-voice",
  "POST /api/v1/knowledge/page-voice/sync",
  "POST /api/v1/knowledge/page-voice/upload",
  "GET /api/v1/knowledge/page-voice/export",
  "POST /internal/cron/billing-lifecycle",
  "POST /api/v1/knowledge/detect-platform",
  "GET /api/v1/commerce/products",
  "GET /api/v1/commerce/wordpress/status",
  "POST /api/v1/commerce/wordpress/connect",
  "POST /api/v1/commerce/wordpress/sync",
  "DELETE /api/v1/commerce/wordpress",
  "GET /api/v1/commerce/wordpress/widget-bootstrap",
  "GET /api/v1/commerce/shopify/status",
  "POST /api/v1/commerce/shopify/connect",
  "POST /api/v1/commerce/shopify/connect-store",
  "POST /api/v1/commerce/shopify/sync",
  "DELETE /api/v1/commerce/shopify",
  "GET /api/v1/commerce/shopify/widget-bootstrap",
  "GET /api/v1/commerce/shopify/widget",
  "PATCH /api/v1/commerce/shopify/widget",
  "GET /api/v1/team",
  "PATCH /api/v1/team/:userId",
  "DELETE /api/v1/team/:userId",
  "POST /api/v1/chat",
  "GET /api/v1/tenants/me/usage",
  "POST /api/v1/tenants/me/widget/regenerate-key",
  "GET /api/v1/conversations",
  "GET /api/v1/conversations/:id",
  "GET /api/v1/conversations/:id/messages",
  "PATCH /api/v1/conversations/:id/handling",
  "POST /api/v1/conversations/:id/reply",
  "GET /api/v1/widget/config",
  "POST /api/v1/widget/chat",
  "GET /api/v1/dashboard/stats",
  "GET /api/v1/analytics",
  "POST /api/v1/devices/register",
  "DELETE /api/v1/devices/register",
  "GET /api/v1/channels",
  "POST /api/v1/channels/meta/connect",
  "POST /api/v1/channels/meta/connect-messenger",
  "POST /api/v1/channels/meta/connect-instagram",
  "POST /api/v1/channels/meta/connect-dev",
  "POST /api/v1/channels/meta/connect-messenger-dev",
  "GET /api/v1/channels/meta/dev-status",
  "DELETE /api/v1/channels/meta/:channel",
  "GET /api/v1/channels/meta/health",
  "GET /webhooks/meta",
  "POST /webhooks/meta",
  "GET /api/v1/billing/plans",
  "GET /api/v1/billing/subscription",
  "GET /api/v1/billing/overview",
  "POST /api/v1/billing/checkout",
  "POST /api/v1/billing/cancel",
  "POST /api/v1/billing/reactivate",
  "POST /webhooks/payment",
  "POST /webhooks/commerce/woocommerce",
] as const;

export const REAL_API_DOMAINS = [
  "auth",
  "tenant profile",
  "tenant config",
  "plan limits",
  "onboarding",
  "knowledge",
  "chat",
  "usage",
  "conversations",
  "widget",
  "dashboard",
  "analytics",
  "devices",
  "channels",
  "team",
  "commerce",
  "webhooks",
  "billing",
] as const;
