/** Routes backed by real Lambda handlers + DynamoDB */
export const IMPLEMENTED_ROUTES = [
  "GET /health",
  "POST /auth/signup",
  "POST /auth/login",
  "POST /auth/refresh",
  "POST /auth/logout",
  "POST /auth/forgot-password",
  "POST /auth/reset-password",
  "POST /auth/resend-verification",
  "POST /auth/invite",
  "POST /auth/accept-invite",
  "GET /auth/me",
  "POST /auth/verify-email",
  "GET /api/v1/tenants/me",
  "PATCH /api/v1/tenants/me",
  "POST /api/v1/tenants/me/logo",
  "GET /api/v1/tenants/me/config",
  "PATCH /api/v1/tenants/me/config",
  "GET /api/v1/tenants/me/limits",
  "GET /api/v1/onboarding",
  "PATCH /api/v1/onboarding/step",
  "POST /api/v1/onboarding/test-chat",
  "GET /api/v1/knowledge/sources",
  "POST /api/v1/knowledge/sources",
  "DELETE /api/v1/knowledge/sources/:id",
  "POST /api/v1/knowledge/sources/:id/sync",
  "GET /api/v1/knowledge/jobs",
  "GET /api/v1/knowledge/jobs/:id",
  "POST /api/v1/knowledge/faq",
  "GET /api/v1/commerce/products",
  "GET /api/v1/team",
  "POST /api/v1/chat",
  "GET /api/v1/tenants/me/usage",
  "POST /api/v1/tenants/me/widget/regenerate-key",
  "GET /api/v1/conversations",
  "GET /api/v1/conversations/:id",
  "GET /api/v1/conversations/:id/messages",
  "GET /api/v1/widget/config",
  "POST /api/v1/widget/chat",
  "GET /api/v1/dashboard/stats",
  "GET /api/v1/channels",
  "POST /api/v1/channels/meta/connect",
  "POST /api/v1/channels/meta/connect-dev",
  "GET /api/v1/channels/meta/dev-status",
  "DELETE /api/v1/channels/meta/:channel",
  "GET /api/v1/channels/meta/health",
  "GET /webhooks/meta",
  "POST /webhooks/meta",
] as const;

export const REAL_API_DOMAINS = [
  "auth",
  "tenant profile",
  "tenant config",
  "plan limits",
  "onboarding",
  "knowledge",
  "chat",
  "usage",
  "conversations",
  "widget",
  "dashboard",
  "channels",
  "team",
  "commerce",
  "webhooks",
] as const;
