/** Routes backed by real Lambda handlers + DynamoDB */
export const IMPLEMENTED_ROUTES = [
  "GET /health",
  "POST /auth/signup",
  "POST /auth/login",
  "POST /auth/refresh",
  "POST /auth/logout",
  "POST /auth/forgot-password",
  "POST /auth/reset-password",
  "POST /auth/resend-verification",
  "GET /auth/me",
  "POST /auth/verify-email",
  "GET /api/v1/tenants/me",
  "PATCH /api/v1/tenants/me",
  "GET /api/v1/tenants/me/config",
  "PATCH /api/v1/tenants/me/config",
  "GET /api/v1/tenants/me/limits",
  "GET /api/v1/onboarding",
  "PATCH /api/v1/onboarding/step",
  "POST /api/v1/onboarding/test-chat",
  "GET /api/v1/knowledge/sources",
  "POST /api/v1/knowledge/sources",
  "DELETE /api/v1/knowledge/sources/:id",
  "POST /api/v1/knowledge/sources/:id/sync",
  "GET /api/v1/knowledge/jobs",
  "GET /api/v1/knowledge/jobs/:id",
  "POST /api/v1/chat",
] as const;

export const REAL_API_DOMAINS = [
  "auth",
  "tenant profile",
  "tenant config",
  "plan limits",
  "onboarding",
  "knowledge",
  "chat",
] as const;
