import { normalizeEmail } from "@commercechat/shared";

export const Keys = {
  tenantPk: (tenantId: string) => `TENANT#${tenantId}`,
  profile: () => "PROFILE",
  config: () => "CONFIG",
  limits: () => "LIMITS",
  user: (userId: string) => `USER#${userId}`,
  session: (sessionId: string) => `SESSION#${sessionId}`,
  emailLookupPk: (email: string) => `EMAIL#${normalizeEmail(email)}`,
  emailLookupSk: () => "USER",
  tokenPk: (hash: string) => `TOKEN#${hash}`,
  tokenSk: () => "META",
  refreshLookupPk: (hash: string) => `REFRESH#${hash}`,
  refreshLookupSk: () => "SESSION",
  apiKeyPk: (hash: string) => `APIKEY#${hash}`,
  apiKeySk: () => "TENANT",
  onboardingState: () => "ONBOARDING#STATE",
  source: (sourceId: string) => `SOURCE#${sourceId}`,
  job: (jobId: string) => `JOB#${jobId}`,
  product: (sku: string) => `PRODUCT#${sku}`,
  conversation: (channel: string, externalUserId: string) => `CONV#${channel}#${externalUserId}`,
  message: (conversationId: string, timestamp: string) => `MSG#${conversationId}#${timestamp}`,
  cart: (conversationId: string) => `CART#${conversationId}`,
  usage: (period: string) => `USAGE#${period}`,
  channel: (channel: string) => `CHANNEL#${channel}`,
  phoneRoutingPk: (phoneNumberId: string) => `PHONE#${phoneNumberId}`,
  phoneRoutingSk: () => "TENANT",
  idempotency: (key: string) => `IDEMPOTENCY#${key}`,
};
